let users = [{
    "id": 1,
    "name": "lkornel0",
    "email": "hisson0@businessweek.com"
  }, {
    "id": 2,
    "name": "mmallett1",
    "email": "sriordan1@phoca.cz"
  }, {
    "id": 3,
    "name": "smegson2",
    "email": "cprydie2@friendfeed.com"
  }, {
    "id": 4,
    "name": "bvondruska3",
    "email": "bbezemer3@answers.com"
  }, {
    "id": 5,
    "name": "ttripe4",
    "email": "erubinowitch4@phpbb.com"
  }, {
    "id": 6,
    "name": "hlefeaver5",
    "email": "khicklingbottom5@addthis.com"
  }, {
    "id": 7,
    "name": "wbrognot6",
    "email": "kduncklee6@ftc.gov"
  }, {
    "id": 8,
    "name": "vsanham7",
    "email": "tbarke7@home.pl"
  }, {
    "id": 9,
    "name": "jconnop8",
    "email": "gcurado8@time.com"
  }, {
    "id": 10,
    "name": "tpreble9",
    "email": "gharris9@freewebs.com"
  }, {
    "id": 11,
    "name": "mjirusa",
    "email": "gangela@scribd.com"
  }, {
    "id": 12,
    "name": "smanilob",
    "email": "brabbetb@imageshack.us"
  }, {
    "id": 13,
    "name": "edainesc",
    "email": "mreamc@salon.com"
  }, {
    "id": 14,
    "name": "dheymannd",
    "email": "jfirbyd@delicious.com"
  }, {
    "id": 15,
    "name": "dlyttlee",
    "email": "gdriffielde@cloudflare.com"
  }, {
    "id": 16,
    "name": "rwakelinf",
    "email": "fcausticf@biglobe.ne.jp"
  }, {
    "id": 17,
    "name": "jlachaizeg",
    "email": "ekennsleyg@acquirethisname.com"
  }, {
    "id": 18,
    "name": "nkimptonh",
    "email": "kjansikh@reference.com"
  }, {
    "id": 19,
    "name": "jcammoilei",
    "email": "mdawnayi@indiegogo.com"
  }, {
    "id": 20,
    "name": "wawdryj",
    "email": "cwalkeyj@mozilla.org"
  }]
for (let i =0 ; i<=users.length-1 ; i++){
    console.log(users[i].id)
} 